repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args: [ "--line-length=100", "--select=E,F,N"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ "--line-length=100" ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        args: [ "--line-length=100", "--check"]
      - id: nbqa-isort
        args: [ "--float-to-top", "--profile=black", "--check-only"]
      - id: nbqa-ruff
        args: [ "--line-length=100" , "--select=E,F,N"]

  # check for private keys and passwords!
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
