version:  '3.8'
services:
    {{ cookiecutter.project_slug }}-notebooks:
      build:
        context: .
      volumes:
        - ./data:/home/mambauser/data
        - ./notebooks:/home/mambauser/notebooks
        - ./src:/home/mambauser/src
      ports:
        - 8888:8888
        - 8787:8787  # dask dashboard
      container_name: {{ cookiecutter.project_slug }}_notebooks
